server:
  port: 8082

spring:
  application:
    name: news-service
  datasource:
    url: jdbc:mysql://localhost:3306/newsapp_news
    username: root
    password: Chinmay@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
news:
  api:
    key: ${NEWS_API_KEY}
    url: https://newsapi.org/v2

