server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/newsapp_users
    username: root
    password: Chinmay@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# JWT
jwt:
  secret=newsapp_secret_key_which_is_very_long_for_security
  expiration=86400000